module.exports = {
	GOOGLEMAPS: "YOUR GOOGLE MAPS KEY HERE",
	UBER: "YOUR UBER DEVELOPER KEY HERE",
	UBERCLIENTID: "YOUR UBER CLIENT ID HERE",
	UBERCLIENTSECRET: "YOUR UBER CLIENT SECRET HERE",
	UBERSERVERTOKEN: "YOUR UBER SERVER TOKEN HERE",
	UBERPASSPORTCALLBACKURL: "YOUR UBER-PASSPORT CALLBACK URL HERE",
	MONGODB_URI: 'YOUR MONGODB URI HERE',
	SECRET: 'YOUR SECRET KEY HERE'
};
